<h1>Статьи</h1>
<a href="/admin/article/add/">Добавить</a>
<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
            <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

    echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Категория</th>
            <th>Заголовок</th>
            <th>Статья</th>
            <th>Начало статьи</th>
            <th>Опубликовано</th>
            <th>Действие</th>
        </tr>

        <?php
            foreach ($articles as $item) {
                $category = $item->getCategory();
                if ($category) {
                    $catName = $category->getCategoryName();
                } else {
                    $catName = '';
                }

                if ($item->getIsPublic()) {
                    $isPublic = 'Да';
                } else {
                    $isPublic = 'Нет';
                }

                $tr = "<tr>";
                $tr .= "
                    <td>{$item->getId()}</td>
                    <td>{$catName}</td>
                    <td>{$item->getTitle()}</td>
                    <td>{$item->getArticleForTable()}</td>
                    <td>{$item->getShortArticleForTable()}</td>
                    <td>{$isPublic}</td>
                ";
                $tr .= "<td>
                    <a href=\"{$this->url('admin/article', ['action' => 'edit', 'id' => $item->getId()])}\">Редактировать</a>&nbsp;&nbsp;
                    <a href=\"{$this->url('admin/article', ['action' => 'delete', 'id' => $item->getId()])}\" onclick=\"if (confirm('Удалить запись?')) { window.location = this.href; } return false;\">Удалить</a>
                </td>";
                $tr .= "</tr>";
                echo $tr;
            }
        ?>
    </tbody>
</table>

<?php

echo $this->paginationControl($articles,
                                'Sliding',
                                'pagination_control',
                                array('route' => 'admin/article')
);