<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">

        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li class="page-item"><a class="page-link" href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
                <<
            </a></li>
        <?php else: ?>
            <li class="page-item disabled"><a class="page-link" href="#" onclick="return false;">
                <<
            </a></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url($this->route); ?>?page=<?php echo $page; ?>">
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item active">
                    <a class="page-link" href="#"><?php echo $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li class="page-item"><a class="page-link" href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                    >>
                </a></li>
        <?php else: ?>
            <li class="page-item disabled"><a class="page-link" href="#" onclick="return false;">
                    >>
                </a></li>
        <?php endif; ?>

    </ul>
<?php endif; ?>
